name = "LoVe"
defaultTargets = ["LoVe"]

[leanOptions]
autoImplicit = false
linter.unusedVariables = false 

[moreServerOptions]
linter.unusedTactic = false
linter.unreachableTactic = false

[[require]]
name = "mathlib"
git = "https://github.com/leanprover-community/mathlib4.git"
rev = "a719ba5c3115d47b68bf0497a9dd1bcbb21ea663"

[[require]]
name = "autograder" 
git = "https://github.com/robertylewis/lean4-autograder-main" 
rev = "baa159d7ce1e09469c4113c57b018395d2c13ade"

[[lean_lib]]
name = "LoVe"